  import React, { useState } from 'react';
  import { CategoryType } from '../constants';

  const UnifiedLedger = ({ expenses, onRemove, salary, user }) => {
    const [search, setSearch] = useState('');
    const [filter, setFilter] = useState('All');

    const filtered = expenses
      .filter(e => filter === 'All' || e.category === filter)
      .filter(e => e.label.toLowerCase().includes(search.toLowerCase()) || e.notes?.toLowerCase().includes(search.toLowerCase()))
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    const exportPDF = () => {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const now = new Date();
      const monthYear = now.toLocaleString('default', { month: 'long', year: 'numeric' });

      doc.setFillColor(30, 30, 60);
      doc.rect(0, 0, pageWidth, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(`${user?.displayName || 'My'} - Expense Report`, pageWidth / 2, 18, { align: 'center' });
      doc.setFontSize(10);
      doc.setTextColor(160, 160, 220);
     doc.text(`${monthYear} | ${now.toLocaleDateString()}`, pageWidth / 2, 30, { align: 'center' });

      const total = filtered.reduce((sum, e) => sum + e.amount, 0);
const remaining = (salary || 0) - total;
doc.setFontSize(10);
doc.setTextColor(30, 30, 30);
doc.setFont('helvetica', 'normal');
doc.text(`Total Records: ${filtered.length}`, 14, 52);

doc.setFontSize(14);
doc.setFont('helvetica', 'bold');
doc.setTextColor(30, 30, 30);
doc.text(`Total Salary:  Rs. ${(salary || 0).toLocaleString()}`, 14, 62);

doc.setFontSize(14);
doc.setFont('helvetica', 'normal');
doc.setTextColor(200, 60, 60);
doc.text(`Total Spent:   Rs. ${total.toLocaleString()}`, 14, 72);

doc.setFontSize(14);
doc.setFont('helvetica', 'bold');
doc.setTextColor(remaining < 0 ? 200 : 20, remaining < 0 ? 30 : 140, 30);
doc.text(`Balance:       Rs. ${remaining.toLocaleString()}`, 14, 82);

let y = 95;
      doc.setFillColor(60, 60, 120);
      doc.rect(10, y - 7, pageWidth - 20, 10, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text('Date', 14, y);
      doc.text('Description', 45, y);
      doc.text('Category', 110, y);
      doc.text('Method', 145, y);
      doc.text('Amount (Rs.)', 175, y, { align: 'right' });
      y += 8;

      filtered.forEach((exp, i) => {
        if (y > 270) { doc.addPage(); y = 20; }
        if (i % 2 === 0) {
          doc.setFillColor(245, 245, 255);
          doc.rect(10, y - 5, pageWidth - 20, 9, 'F');
        }
        doc.setTextColor(40, 40, 40);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(new Date(exp.date).toLocaleDateString(), 14, y);
        doc.text(exp.label.substring(0, 30), 45, y);
        doc.text(exp.category.split(' / ')[0].substring(0, 18), 110, y);
        doc.text(exp.paymentMethod || 'UPI', 145, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(20, 120, 80);
        doc.text(exp.amount.toLocaleString(), 175, y, { align: 'right' });
        y += 9;
      });

      y += 4;
      doc.setDrawColor(100, 100, 200);
      doc.line(10, y, pageWidth - 10, y);
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      doc.text('TOTAL', 145, y);
      doc.setTextColor(20, 120, 80);
      doc.text(`Rs. ${total.toLocaleString()}`, 175, y, { align: 'right' });

      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.setFont('helvetica', 'italic');
      doc.text(`Generated by Wealth Hub on ${now.toLocaleString()}`, pageWidth / 2, 290, { align: 'center' });

      doc.save(`expenses-${monthYear.replace(' ', '-')}.pdf`);
    };

    return (
      <div className="space-y-6">
        <div className="flex flex-col md:flex-row gap-4 justify-between items-start md:items-center bg-slate-800/20 p-4 rounded-3xl border border-slate-800/50">
          <div className="relative w-full md:w-80">
            <i className="fa-solid fa-magnifying-glass absolute left-3 top-1/2 -translate-y-1/2 text-slate-600 text-xs"></i>
            <input
              type="text"
              placeholder="Filter records..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full bg-slate-950/50 border border-slate-700 rounded-xl pl-9 pr-4 py-3 text-xs focus:ring-2 focus:ring-emerald-500/30 outline-none text-slate-200"
            />
          </div>
          <div className="flex gap-2 w-full md:w-auto overflow-x-auto pb-2 md:pb-0 scrollbar-hide">
            {['All', ...Object.values(CategoryType)].map((cat) => (
              <button
                key={cat}
                onClick={() => setFilter(cat)}
                className={`px-4 py-2.5 rounded-xl text-[10px] font-black uppercase whitespace-nowrap transition-all border ${
                  filter === cat ? 'bg-emerald-500 text-white shadow-lg shadow-emerald-500/20 border-emerald-400' : 'bg-slate-900 text-slate-500 border-slate-800 hover:text-slate-300'
                }`}
              >
                {cat.split(' / ')[0]}
              </button>
            ))}
          </div>
          <button
            onClick={exportPDF}
            className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-[10px] font-black uppercase tracking-widest transition-all shadow-lg shadow-indigo-600/30 whitespace-nowrap border border-white/10 active:scale-95"
          >
            <i className="fa-solid fa-file-pdf"></i>
            Export PDF
          </button>
        </div>

        <div className="bg-slate-800/20 rounded-[2rem] border border-slate-800 overflow-hidden shadow-2xl">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[700px]">
              <thead>
                <tr className="border-b border-slate-800 bg-slate-900/50">
                  <th className="p-5 text-[10px] font-black uppercase text-slate-500 tracking-widest">Timestamp</th>
                  <th className="p-5 text-[10px] font-black uppercase text-slate-500 tracking-widest">Entry Detail</th>
                  <th className="p-5 text-[10px] font-black uppercase text-slate-500 tracking-widest">Classification</th>
                  <th className="p-5 text-[10px] font-black uppercase text-slate-500 tracking-widest">Gateway</th>
                  <th className="p-5 text-[10px] font-black uppercase text-slate-500 tracking-widest text-right">Value</th>
                  <th className="p-5"></th>
                </tr>
              </thead>
              <tbody>
                {filtered.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="p-16 text-center text-slate-600 italic text-sm">No transaction records found in the vault.</td>
                  </tr>
                ) : (
                  filtered.map((exp) => (
                    <tr key={exp.id} className="border-b border-slate-800/40 hover:bg-slate-700/10 transition-colors group">
                      <td className="p-5 text-xs font-mono text-slate-500">{new Date(exp.date).toLocaleDateString()}</td>
                      <td className="p-5">
                        <p className="text-sm font-bold text-slate-100">{exp.label}</p>
                        {exp.notes && <p className="text-[10px] text-slate-500 italic mt-1 line-clamp-1">{exp.notes}</p>}
                      </td>
                      <td className="p-5">
                        <span className="text-[9px] font-black uppercase text-slate-400 bg-slate-900/80 px-2.5 py-1 rounded-lg border border-slate-700">
                          {exp.category.split(' / ')[0]}
                        </span>
                      </td>
                      <td className="p-5 text-[10px] font-black text-slate-500 uppercase tracking-tighter">{exp.paymentMethod || 'UPI'}</td>
                      <td className="p-5 text-right font-mono font-black text-emerald-400 text-base">₹{exp.amount.toLocaleString()}</td>
                      <td className="p-5 text-right">
                        <button
                          onClick={() => onRemove(exp.id)}
                          className="size-8 rounded-lg bg-rose-500/5 text-slate-600 hover:text-rose-500 hover:bg-rose-500/10 transition-all flex items-center justify-center"
                          title="Delete record"
                        >
                          <i className="fa-solid fa-trash-can text-[11px]"></i>
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    );
  };

  export default UnifiedLedger;
